### 查USER - page
GET http://localhost:8080/api/user?
    page=0
    &size=10
    &uuid=
    &account=
    &status=1
Authorization: Bearer {{bearer-admin}}


### 查USER - uuid
GET http://localhost:8080/api/user/f41d153a-a81f-4e07-a2a4-fc205725e623
Content-Type: application/json
Authorization: Bearer {{bearer-admin}}

### 新增user
POST http://localhost:8080/api/user
Content-Type: application/json
Authorization: Bearer {{bearer-admin}}

{
  "account": "admin2",
  "password": "123456",
  "remark": "建立admin",
  "sysRole": ["ADMIN"]
}


### 改user -(不含密碼)
PUT http://localhost:8080/api/user/f41d153a-a81f-4e07-a2a4-fc205725e623
Content-Type: application/json
Authorization: Bearer {{bearer-admin}}

{
  "uuid": "f41d153a-a81f-4e07-a2a4-fc205725e623",
  "password": "{{$random.alphanumeric(6)}}",
  "remark": "修改user{{$random.alphanumeric(6)}}",
  "sysRole": ["MERCHANTS"]
}

### 改user (密碼)
PUT http://localhost:8080/api/user/pw/f41d153a-a81f-4e07-a2a4-fc205725e623
Content-Type: application/json
Authorization: Bearer {{bearer-admin}}

{
  "uuid": "3c63796c-b54f-4788-967d-2040ab1e6969",
  "password": "1234567",
  "remark": "修改密碼user{{$random.alphanumeric(6)}}"
}

### 刪除使用者 uuid
DELETE http://localhost:8080/api/user/3c63796c-b54f-4788-967d-2040ab1e6969
Content-Type: application/json
Authorization: Bearer {{bearer-admin}}



