###login 取得token
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "account": "admin",
  "password": "123456",
  "code": "1234"
}

###refresh
POST http://localhost:8080/auth/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50IjoiYWRtaW4iLCJudW0iOjEsInJvbGVzIjpbIkFETUlOIl0sImV4cCI6MTc0MzkzMDgwMywiaXNzIjoiand0LWRlbW8tYXBpIiwiaWF0IjoxNzM2NzMwODAzfQ.rwEV5Asc5GgXdzj49Npn1P-3xzsn_RlNlsN_L74a1u0
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50IjoiYWRtaW4iLCJudW0iOjEsInJvbGVzIjpbIkFETUlOIl0sImV4cCI6MTc0MzkzMDgwMywiaXNzIjoiand0LWRlbW8tYXBpIiwiaWF0IjoxNzM2NzMwODAzfQ.rwEV5Asc5GgXdzj49Npn1P-3xzsn_RlNlsN_L74a1u0

{
  "account": "admin"
}