###rex
POST http://localhost:8080/api/hello/rex
Content-Type: application/json

{
  "account": "admin",
  "password": "123456"
}

###login 取得token
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "account": "admin",
  "password": "123456",
  "code": "1234"
}



###
POST http://localhost:8080/api/hello/p/jwt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50IjoiYWRtaW4iLCJyb2xlcyI6WyJBRE1JTiJdLCJleHAiOjE3MzYzMDkzMjEsImlzcyI6ImRlbW8tYXBpIiwiaWF0IjoxNzM2MzAyMTIxfQ.FigVQLYYRymTFeqQaSeXgl7ohZDwoAOvk56r8clCfp8

{
  "username": "admin"
}



###
POST http://localhost:8080/auth/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50IjoiYWRtaW4iLCJudW0iOjEsInJvbGVzIjpbIkFETUlOIl0sImV4cCI6MTc0MzkzMDgwMywiaXNzIjoiand0LWRlbW8tYXBpIiwiaWF0IjoxNzM2NzMwODAzfQ.rwEV5Asc5GgXdzj49Npn1P-3xzsn_RlNlsN_L74a1u0
cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50IjoiYWRtaW4iLCJudW0iOjEsInJvbGVzIjpbIkFETUlOIl0sImV4cCI6MTc0MzkzMDgwMywiaXNzIjoiand0LWRlbW8tYXBpIiwiaWF0IjoxNzM2NzMwODAzfQ.rwEV5Asc5GgXdzj49Npn1P-3xzsn_RlNlsN_L74a1u0

{
  "account": "admin"
}




### 寫入Cookie 練習
GET http://localhost:8080/hello/g/cookie-demo?
    account={{$random.alphanumeric(8)}}